[package]
name = "ds-rs"
version = "0.1.0"
authors = ["Redrield <redrield@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0.4"
byteorder = "1.2.7"
failure = "0.1.3"
chrono = "0.4.6"
gilrs = "0.6.1"
crossbeam-channel = "0.3.2"
termion = "1.5.1"
